# Generated by Django 5.2.16 on 2026-07-28 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(default='Assistant Professor', max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('assigned_sections', models.ManyToManyField(blank=True, related_name='assigned_faculty', to='subjects.section')),
                ('assigned_subjects', models.ManyToManyField(blank=True, related_name='assigned_faculty', to='subjects.subject')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='departments.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['employee_id'],
            },
        ),
    ]
